import fs from "node:fs"
import path from "node:path"

const ROOT = process.cwd()
const DATA_DIR = path.join(ROOT, "src", "data", "questions")
const AGG_OUT = path.join(ROOT, "src", "data", "questions.ts")

export interface DataEntry {
  id: string
  topic: string
  image: string
  answer: "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h"
}

export function writeExamJson(examId: string, entries: DataEntry[]): void {
  fs.mkdirSync(DATA_DIR, { recursive: true })
  const out = path.join(DATA_DIR, `${examId}.json`)
  fs.writeFileSync(out, JSON.stringify(entries, null, 2) + "\n")
}

export function regenerateAggregate(): void {
  fs.mkdirSync(DATA_DIR, { recursive: true })
  const files = fs
    .readdirSync(DATA_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort()

  const all: DataEntry[] = []
  const exams: string[] = []
  for (const f of files) {
    const raw = fs.readFileSync(path.join(DATA_DIR, f), "utf8")
    const arr = JSON.parse(raw) as DataEntry[]
    all.push(...arr)
    exams.push(f.replace(/\.json$/, ""))
  }

  const banner = `// AUTO-GENERATED by scripts/ingest-year.ts. Do not edit by hand.
// Regenerated: ${new Date().toISOString()}
// Source exams (${exams.length}): ${exams.join(", ") || "none"}
// Topic field is a placeholder ("uncategorized") until manual classification.
`

  const body = `${banner}
import type { ChoiceId } from "@/lib/questions"

export interface RawQuestion {
  id: string
  topic: string
  image: string
  answer: ChoiceId
}

export const QUESTIONS: readonly RawQuestion[] = ${JSON.stringify(all, null, 2)} as const
`
  fs.writeFileSync(AGG_OUT, body)
}
